"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

def main():
    a = 1
    b = 2
    c = 3
    ans = 0
    while b <= 4000000:
        ans += b
        a = b + c
        b = c + a
        c = a + b
    print(ans)

if __name__ == '__main__':
    main()
